import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const calendasPlusBold = localFont({
  src: "./fonts/CalendasPlusBold.woff2",
  variable: "--font-calendas-plus-serif",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${calendasPlusBold.variable}`}>
        <header className="flex flex-col items-center justify-center py-6 px-2">
          <div className="flex flex-col items-center justify-center gap-1 flex-1">
            <h1 className="text-5xl font-serif">Ten Million Checkboxes</h1>
            <p className="text-neutral-600 italic">
              (checking a box checks it for everyone!)
            </p>
          </div>

          <div className="flex items-start w-full">
            <p>
              an idea by{" "}
              <a
                href="https://eieio.games"
                rel="noopener noreferrer"
                className="text-blue-500 hover:text-blue-900 focus:text-blue-900 active:text-blue-900"
              >
                eieio
              </a>{" "}
              stolen by{" "}
              <a
                href="https://x.com/KacperOchmanski"
                rel="noopener noreferrer"
                className="text-blue-500 hover:text-blue-900 focus:text-blue-900 active:text-blue-900"
              >
                kacper
              </a>
            </p>
          </div>
        </header>

        {children}
      </body>
    </html>
  );
}
